

// // fonts
// import { Lato, Montserrat, Poppins, Raleway, } from '@next/font/google';
// import AdminHeader from '../../componentsAdmin/Header/AdminHeader'
// import AdminFooter from '../../componentsAdmin/Footer/AdminFooter'
// import '../globals.scss';

// // fonts
// const raleway = Raleway({
//   weight: ['400', '700', '800', '900'],
//   subsets: ['latin'],
// });
// const lato = Lato({
//   weight: ['400', '700','900'],
//   subsets: ['latin'],
// });
// const montserrat = Montserrat({
//   weight: ['400', '700', '800', '900'],
//   subsets: ['latin'],
// });
// const poppins = Poppins({
//   weight: ['400','500', '700', '800', '900'],
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



// export default function RootLayout({ children }) {
  
//   return (
//     <html lang="en">
//       <body className={`${lato.className} ${raleway.className} ${montserrat.className} ${poppins.className}`}>
//         <AdminHeader />
//         {children}
//         {/* <AdminFooter /> */}
//       </body>
//     </html>
//   );
// }

